language: node_js

node_js:
    - "node"
    - "12"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov

notifications:
    webhooks:
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always

env:
  - JWT_SECRET=WGKvGsFnXBMb5dXGLHqVBcTUJReRQUumgZQYt8Rmp6XZsHMUMRUzKUDrwAPeBdef
  - JWT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRvZSIsImlhdCI6MTYwMTE1MTM5NSwiZXhwIjoxNjMyNjg3Mzk1fQ.D_mEJZXMQ7XKFPR0y6fECy1tM9YkgP1HuLpIFnbhYuE